### ISSUE TITLE
typo in demo

### ISSUE THREAD

**Issue by andrewshulmantime** [the-road-to-graphql/node-apollo-boost-github-graphql-api#6]
https://github.com/the-road-to-graphql/node-apollo-boost-github-graphql-api/blob/master/src/index.js#L57

Should it be:
```
console.log('first page', edges.length);
```

**Comment by rwieruch** [comment]
You are correct! Can you open a Pull Request for the fix? :)

**Comment by andrewshulmantime** [comment]
I'd be happy to and tried creating a PR before I opened the issue.  But I didn't seem to have permission:

```
$ git push origin fix-label-in-console-output
remote: Permission to the-road-to-graphql/node-apollo-boost-github-graphql-api.git denied to andrewshulmantime.
fatal: unable to access 'https://github.com/the-road-to-graphql/node-apollo-boost-github-graphql-api.git/': The requested URL returned error: 403
```

**Comment by rwieruch** [comment]
Yes. You need to create a fork of this repository and from there push to your forked copy of this repository. Then you can create a PR from there. Otherwise everyone could easily push to third-party repositories without permission :)

**Comment by rwieruch** [comment]
Fixed in https://github.com/the-road-to-graphql/node-apollo-boost-github-graphql-api/commit/03040945cce008192be27fe646ec1b49654bf30d
